### ISSUE TITLE
Get-O365Domain 401 (Unauthorized)

### ISSUE THREAD

**Issue by krzydoug** [EvotecIT/O365Essentials#19]
Both attempts result in the same error of 

`
WARNING: Invoke-O365Admin - Error: Response status code does not indicate success: 401 (Unauthorized).
`

Attempt 1 
`
Connect-O365Admin
Get-O365Domain
`

Attempt2
`
Get-O365Domain  # browser window opens and authentication complete
`

There are several commands that either give 401 or  403. I did not see any required setting changes in the documentation. The first example is connect and then Get-O365Domain.

**Comment by PrzemyslawKlys** [comment]
Well, I was testing this with the Global Admin account. I would expect Global Reader would work. 

What are you using to access that data?

**Comment by krzydoug** [comment]
I am using a Global Admin account.

**Comment by PrzemyslawKlys** [comment]
Is it working now or still an issue?

**Comment by krzydoug** [comment]
`
PS C:\Users\Doug> Connect-O365Admin

Name                           Value
----                           -----
Credential
UserName                       dmaurer@domainname.com
Environment                    AzureCloud
Subscription
Tenant                         7d68rest-of-guid
ExpiresOnUTC                   9/28/2021 8:05:09 PM
AuthenticationO365             Microsoft.Azure.PowerShell.Authenticators.MsalAccessToken
AccessTokenO365                redacted
HeadersO365                    {Content-Type, Authorization, X-Requested-With, x-ms-client-request-id…}
AuthenticationAzure            Microsoft.Azure.PowerShell.Authenticators.MsalAccessToken
AccessTokenAzure               redacted
HeadersAzure                   {Content-Type, Authorization, X-Requested-With, x-ms-client-request-id…}
AuthenticationGraph            Microsoft.Azure.PowerShell.Authenticators.MsalAccessToken
AccessTokenGraph               redacted
HeadersGraph                   {Content-Type, Authorization, X-Requested-With, x-ms-client-request-id…}

PS C:\Users\Doug> Get-O365Domain
WARNING: Invoke-O365Admin - Error: Response status code does not indicate success: 401 (Unauthorized).
PS C:\Users\Doug> Get-O365AzureADConnect
WARNING: Invoke-O365Admin - Error: Response status code does not indicate success: 403 (Forbidden).

passwordSyncStatus               : False
verifiedDomainCount              :
verifiedCustomDomainCount        :
federatedDomainCount             :
numberOfHoursFromLastSync        :
dirSyncEnabled                   :
dirSyncConfigured                :
passThroughAuthenticationEnabled :
seamlessSingleSignOnEnabled      :


PS C:\Users\Doug> Get-O365User
WARNING: Invoke-O365Admin - Error: Response status code does not indicate success: 403 (Forbidden). Insufficient privileges to complete the operation.
PS C:\Users\Doug> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.9
PSEdition                      Core
GitCommitId                    7.2.0-preview.9
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

`

**Comment by PrzemyslawKlys** [comment]
$Headers = Connect-O365Admin
ConvertFrom-JsonWebToken -Token $Headers.AccessTokenO365 

Does that show you proper token information?

**Comment by PrzemyslawKlys** [comment]
Get-Module -listavailable az.accounts

**Comment by PrzemyslawKlys** [comment]
Also, can you try on some clean machine? Maybe something gets cached locally and is getting used somehow?

**Comment by krzydoug** [comment]
![image](https://user-images.githubusercontent.com/26283595/135153695-ec92da13-2ca8-48c2-8bdb-9b5d9a5a0e1d.png)
![image](https://user-images.githubusercontent.com/26283595/135153774-742e71aa-2cac-4042-a4a7-c76428c02eb2.png)

**Comment by PrzemyslawKlys** [comment]
can you leave only 2.5.3 ? The rest seems ok. The only thing that differs for me is region scope (EU for me)

**Comment by krzydoug** [comment]
Brand new windows 10 machine, brand new install of pwsh
![image](https://user-images.githubusercontent.com/26283595/135155120-18fd887c-6c88-4555-9508-87f319b59fa8.png)

**Comment by PrzemyslawKlys** [comment]
You got any other tenants to check?

**Comment by krzydoug** [comment]
Brand new windows 10 pc, fresh install of pwsh
![image](https://user-images.githubusercontent.com/26283595/135155340-cc18ebf2-d193-4361-9a87-efea7383369e.png)

**Comment by krzydoug** [comment]
I do have other tenants, and I just tested one and it worked. So it's something about this tenant or this admin account. I'll test with another account and let you know. Appreciate all the work you put in and share with us.
