### ISSUE TITLE
Humble sumission for function help

### ISSUE THREAD

**Issue by neztach** [EvotecIT/O365Essentials#29]
I took curser.sh and leveraged it to add function help for O365Essentials in hopes that it may be of some use to you for documentation.

Please have a look and I sincerely hope it helps you and this project.
https://github.com/neztach/PS-Public/blob/master/evotec-O365Essentials.ps1

**Comment by PrzemyslawKlys** [comment]
Hi,

I have no use for it if its not provided as PR and added directly to sources. Using my main psm1 and modifying it would mean i need to reapply whatever you created and spend lots of time on applying it to sources. 

If you can learn PR on github I'm sure more docs would help.

**Comment by neztach** [comment]
I created a fork, and put my edits there.  Will that work?

https://github.com/neztach/O365Essentials/tree/master

**Comment by PrzemyslawKlys** [comment]
Yes, you then create PR from it:

![image](https://github.com/EvotecIT/O365Essentials/assets/15063294/f2131fe6-367b-42da-b0d8-3ad4ebfe441d)

However 2 things I would like to ask:

1. Each file you remove and add last lines? Not sure if necessary?

![image](https://github.com/EvotecIT/O365Essentials/assets/15063294/bf808173-7947-4964-8ebf-04f92ff7924f)

2. I believe the formatting looks better in this way? So basically one line white space and  without additional tab would be better

![image](https://github.com/EvotecIT/O365Essentials/assets/15063294/12f41494-9418-4763-84d1-0d5d7683092e)

**Comment by neztach** [comment]
gotcha!  OK I'll go through and remedy those, and then I guess submit another pull request?

**Comment by neztach** [comment]
ok help updated as requested.  Please let me know what else I can help with.

**Comment by PrzemyslawKlys** [comment]
What about:

![image](https://github.com/EvotecIT/O365Essentials/assets/15063294/d7c9b06f-f259-478e-a379-5e51d1462672)

It seems to be in every file? Btw you don't need to commit per file, you can bundle it up under one commit ;)

**Comment by neztach** [comment]
I honestly have no idea.  After I forked your repo, I went through the regular Github web interface and edited each file only to add the help, then saved.  I didn't mess with any other parts of the code.

**Comment by PrzemyslawKlys** [comment]
You should try VSCode - doing it via GitHub Web is painful. I'll take a look how to fix it.

**Comment by neztach** [comment]
pulled my fork into curser with git, finished adding help to functions I previously missed.  Still don't see the double close curly brace.  But you were right of course, single pull - make all changes - stange with comment - single push - easy.

At least I got through my previously missed function help.

**Comment by PrzemyslawKlys** [comment]
Thanks mate, took a while to release but it's here
